# Generated by Django 4.1.7 on 2023-03-15 09:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('userid', models.CharField(db_index=True, max_length=30, primary_key=True, serialize=False, unique=True)),
                ('user_username', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('user_fullname', models.CharField(max_length=255)),
                ('user_dob', models.DateField(blank=True, null=True)),
                ('user_email', models.EmailField(db_index=True, max_length=255, unique=True)),
                ('user_callphone', models.CharField(blank=True, db_index=True, max_length=30, null=True, unique=True)),
                ('user_country', models.CharField(blank=True, max_length=200, null=True)),
                ('user_state_divition', models.CharField(blank=True, max_length=200, null=True)),
                ('user_playing_city', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('user_photopath', models.CharField(blank=True, max_length=200, null=True)),
                ('user_life_history', models.JSONField(blank=True, null=True)),
                ('user_playing_sports', models.JSONField(blank=True, null=True)),
                ('user_interested_sports', models.JSONField(blank=True, null=True)),
                ('user_configuration', models.JSONField(blank=True, null=True)),
                ('user_device_info', models.JSONField(blank=True, null=True)),
                ('user_type_flag', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('user_created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
