# Generated by Django 4.1.7 on 2023-03-13 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user_table',
        ),
    ]
