# Generated by Django 4.1.7 on 2023-05-28 03:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user_app', '0002_alter_user_user_photopath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_playing_sports',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200, null=True), blank=True, default=list, null=True, size=None),
        ),
    ]
