# Generated by Django 4.1.7 on 2023-03-21 16:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user_app', '0002_alter_user_user_fullname_alter_user_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type_flag',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Player', 'Player'), ('Scorekeeper', 'Scorekeeper'), ('Umpire', 'Umpire')], max_length=200), blank=True, default=list, null=True, size=None),
        ),
    ]
