# Generated by Django 4.1.7 on 2023-05-29 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user_app', '0003_alter_user_user_playing_sports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_photopath',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
