# Generated by Django 4.1.7 on 2023-03-13 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user_app', '0006_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
