# Generated by Django 4.1.7 on 2023-03-13 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user_app', '0007_alter_user_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
    ]
